#!/usr/bin/env bash

YAML=${1}
shift
BUILD_DIR=${1}
shift

SERIAL=$(date -u +%Y%m%d_%H:%M)

pushd ${BUILD_DIR}
distrobuilder --cache-dir cache build-dir ${YAML} rootfs \
    -o image.serial="${SERIAL}" \
    "$@"
distrobuilder --cache-dir cache pack-lxc ${YAML} rootfs \
    -o image.serial="${SERIAL}" \
    "$@"
popd
